spring.application.name=taskflow
spring.sql.init.mode=always
spring.jpa.open-in-view=false

# Trune on the web console h2
spring.h2.console.enabled=true

# Define the route to login
spring.h2.console.path=/h2-console

# make sure that the database always use the same name in memory
spring.datasource.url=jdbc:h2:mem:taskflowdb